/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finance;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Sameera
 */
public class Finance_Search extends javax.swing.JPanel {

    /**
     * Creates new form Finance_Search
     */
    Finance_Main main=new Finance_Main("");
    public Finance_Search() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchbylable = new javax.swing.JLabel();
        txtSearchBy = new javax.swing.JComboBox<>();
        txtSearchValue = new javax.swing.JTextField();
        searchbylable1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(387, 228));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchbylable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchbylable.setText("Search Value");
        add(searchbylable, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        txtSearchBy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSearchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "ID", "Amount" }));
        txtSearchBy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        txtSearchBy.setBackground(new Color(255,255,255));
        add(txtSearchBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, 30));

        txtSearchValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        add(txtSearchValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 180, 30));

        searchbylable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchbylable1.setText("Search By");
        add(searchbylable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel searchbylable;
    private javax.swing.JLabel searchbylable1;
    public javax.swing.JComboBox<String> txtSearchBy;
    public javax.swing.JTextField txtSearchValue;
    // End of variables declaration//GEN-END:variables
}
